FROM golang:1.14.2
WORKDIR /producer
COPY ./producer/main.go ./
COPY ./message ./message
COPY ./pkg ./pkg
RUN go mod init github.com/albertwidi/gonsq_producer && \
    go get -v ./... && \
    CGO_ENABLED=0 GOOS=linux go build -v -o producer main.go

FROM alpine:3.11.6
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=0 /producer/producer .
ENTRYPOINT ["./producer"]