FROM golang:1.14.2
WORKDIR /consumer
COPY ./consumer/main.go ./
COPY ./message ./message
COPY ./pkg ./pkg
RUN go mod init github.com/albertwidi/gonsq_consumer && \
    go get -v ./... && \
    CGO_ENABLED=0 GOOS=linux go build -v -o consumer main.go

FROM alpine:3.11.6
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=0 /consumer/consumer .
ENTRYPOINT ["./consumer"]