version: '3.2'
services:
    nsq_producer:
        build:
            context: .
            dockerfile: Dockerfile.producer
        command:
        - --nsq.topics=foo,bar
        - --nsq.nsqd-address=nsqd:4150
        - --publish.concurrency=1
        - --publish.jitter=0,100
        depends_on:
        - nsqd
        - nsq_consumer

    nsq_consumer:
        build:
            context: .
            dockerfile: Dockerfile.consumer
        ports:
        - "9080:9000"
        command:
        - --server.address=:9000
        - --nsq.topics=foo,bar
        - --nsq.channels=c1,c2,c3
        - --nsq.lookupd-address=nsqlookupd:4161
        - --nsq.concurrency=2
        - --nsq.maxinflight=500
        depends_on: 
        - nsqlookupd

    prometheus:
        image: prom/prometheus:v2.18.1
        container_name: prometheus
        ports:
        - 9090:9090
        command:
        - --config.file=/etc/prometheus/prometheus.yaml
        volumes:
        - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro

    grafana:
        image: grafana/grafana:7.0.1
        ports:
        - "3000:3000"

    nsqlookupd:
        image: nsqio/nsq:v1.2.0
        command: /nsqlookupd
        ports:
        - "4160"
        - "4161"

    nsqd:
        image: nsqio/nsq:v1.2.0
        command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
        depends_on:
        - nsqlookupd
        ports:
        - "4150"
        - "4151"

    nsqadmin:
        image: nsqio/nsq:v1.2.0
        command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
        depends_on:
        - nsqlookupd  
        ports:
        - "4171:4171"