// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message/random.proto

package random_message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Random struct {
	RandomString         string   `protobuf:"bytes,1,opt,name=RandomString,proto3" json:"RandomString,omitempty"`
	RandomNumber         string   `protobuf:"bytes,2,opt,name=RandomNumber,proto3" json:"RandomNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Random) Reset()         { *m = Random{} }
func (m *Random) String() string { return proto.CompactTextString(m) }
func (*Random) ProtoMessage()    {}
func (*Random) Descriptor() ([]byte, []int) {
	return fileDescriptor_38f926270516c23d, []int{0}
}

func (m *Random) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Random.Unmarshal(m, b)
}
func (m *Random) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Random.Marshal(b, m, deterministic)
}
func (m *Random) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Random.Merge(m, src)
}
func (m *Random) XXX_Size() int {
	return xxx_messageInfo_Random.Size(m)
}
func (m *Random) XXX_DiscardUnknown() {
	xxx_messageInfo_Random.DiscardUnknown(m)
}

var xxx_messageInfo_Random proto.InternalMessageInfo

func (m *Random) GetRandomString() string {
	if m != nil {
		return m.RandomString
	}
	return ""
}

func (m *Random) GetRandomNumber() string {
	if m != nil {
		return m.RandomNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*Random)(nil), "random_message.Random")
}

func init() { proto.RegisterFile("message/random.proto", fileDescriptor_38f926270516c23d) }

var fileDescriptor_38f926270516c23d = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2f, 0x4a, 0xcc, 0x4b, 0xc9, 0xcf, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x83, 0xf0, 0xe2, 0xa1, 0x92, 0x4a, 0x01, 0x5c, 0x6c, 0x41, 0x60, 0x11, 0x21, 0x25,
	0x2e, 0x1e, 0x08, 0x2b, 0xb8, 0xa4, 0x28, 0x33, 0x2f, 0x5d, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33,
	0x08, 0x45, 0x0c, 0xa1, 0xc6, 0xaf, 0x34, 0x37, 0x29, 0xb5, 0x48, 0x82, 0x09, 0x59, 0x0d, 0x44,
	0x2c, 0x89, 0x0d, 0x6c, 0x91, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x6c, 0x55, 0x9f, 0x80,
	0x00, 0x00, 0x00,
}
