name: pkg.go.dev

on:
  push:
    branches: [ master ]

jobs:
  pull:
    name: Go-pull-pkg.go.dev
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Pull github.com/albertwidi/gonsq
      run: |
        mkdir /tmp/pull-gonsq && \
        cd /tmp/pull-gonsq && \
        go mod init github.com/albertwidi/gonsq-pull && \
        go get -v github.com/albertwidi/gonsq